<?php

return [
    'date' => '[15 de enero de 2020]',

    'contractual_relationship' => '1. Relación contractual',

    'contractual_relationship_content' => 'Las presentes Condiciones de uso (“Condiciones”) regulan el acceso o uso que usted haga, como persona, desde cualquier país del mundo (excluidos los Estados Unidos y sus territorios y posesiones así como China Continental) de aplicaciones, páginas web, contenido, productos y servicios (los “Servicios”) puestos a disposición por Hard Production, una sociedad por acciones simplificada constituida en Colombia, con domicilio en Calle 7b # 69d - 26, Bogotá D.C., Colombia, inscrita en la Cámara de Comercio de Bogotá con Nit 901293818 y Número de matrícula 3126546(“Hard Production”).
LEA ESTAS CONDICIONES DETENIDAMENTE ANTES DE ACCEDER O USAR LOS SERVICIOS.
Mediante su acceso y uso de los Servicios usted acuerda vincularse jurídicamente por estas Condiciones, que establecen una relación contractual entre usted y Hard Production. Si usted no acepta estas Condiciones, no podrá acceder o usar los Servicios. Estas Condiciones sustituyen expresamente los acuerdos o compromisos previos con usted. Hard Production podrá poner fin de inmediato a estas Condiciones o cualquiera de los Servicios respecto de usted o, en general, dejar de ofrecer o denegar el acceso a los Servicios o cualquier parte de ellos, en cualquier momento y por cualquier motivo.
Se podrán aplicar condiciones suplementarias a determinados Servicios, como políticas para un evento, una actividad o una promoción particular, y dichas condiciones suplementarias se le comunicarán en relación con los Servicios aplicables. Las condiciones suplementarias se establecen además de las Condiciones, y se considerarán una parte de estas, para los fines de los Servicios aplicables. Las condiciones suplementarias prevalecerán sobre las Condiciones en el caso de conflicto con respecto a los Servicios aplicables.
Hard Production podrá modificar las Condiciones relativas a los Servicios cuando lo considere oportuno. Las modificaciones serán efectivas después de la publicación por parte de Hard Production de dichas Condiciones actualizadas en esta ubicación o las políticas modificadas o condiciones suplementarias sobre el Servicio aplicable. Su acceso o uso continuado de los Servicios después de dicha publicación constituye su consentimiento a vincularse por las Condiciones y sus modificaciones.
La recopilación y el uso que hacemos de la información personal en relación con los Servicios es conforme se dispone en la Política de privacidad de Hard Production, disponible en https://www.speeho.com/legal. Hard Production podrá facilitar a un procesador de reclamaciones o a una aseguradora cualquier información necesaria (incluida su información de contacto) si hubiera quejas, disputas o conflictos, que pudieran incluir un accidente, implicándole a usted y a un tercero (incluido la persona que presta el servicio) y dicha información o dichos datos fueran necesarios para resolver la queja, la disputa o el conflicto.',

    'services' => '2. Los Servicios',

    'services_content' => 'Los Servicios constituyen una plataforma de tecnología de economía colaborativa que permite a los usuarios de las aplicaciones móviles de Hard Production o páginas web proporcionadas como parte de los Servicios (cada una, una “Aplicación”) organizar y planear los servicios de logística con terceros proveedores independientes de dichos servicios, incluidos terceros independientes y terceros proveedores logísticos independientes, conforme a un acuerdo con Hard Production o algunos afiliados de Hard Production (“Terceros proveedores”). A no ser que Hard Production lo acepte mediante un contrato separado por escrito con usted, los Servicios se ponen a disposición solo para su uso personal, no comercial. USTED RECONOCE QUE HARD PRODUCTION NO PRESTA SERVICIOS DE ARTISTAS O DE LOGÍSTICA O FUNCIONA COMO UNA EMPRESA DE AGENCIA Y QUE DICHOS SERVICIOS DE ARTISTAS O LOGÍSTICA SE PRESTAN POR TERCEROS CONTRATISTAS INDEPENDIENTES, QUE NO ESTÁN EMPLEADOS POR HARD PRODUCTION NI POR NINGUNA DE SUS AFILIADOS.',

    'license' => 'Licencia',

    'license_content' => 'Sujeto al cumplimiento de estas Condiciones, Hard Production le otorga una licencia limitada, no exclusiva, no sublicenciable, revocable, no transferible para: (i) el acceso y uso de la web y las Aplicaciones en su dispositivo personal solo en relación con su uso de los Servicios; y (ii) el acceso y uso de cualquier contenido, información y material relacionado que pueda ponerse a disposición a través de los Servicios, en cada caso solo para su uso personal, no comercial. Hard Production y sus licenciantes se reservan cualquier derecho que no haya sido expresamente otorgado por el presente.',

    'restrictions' => 'Restricciones',

    'restrictions_content' => 'Usted no podrá: (i) retirar cualquier nota de derechos de autor, marca registrada u otra nota de propiedad de cualquier parte de los Servicios; (ii) reproducir, modificar, preparar obras derivadas sobre los Servicios, distribuir, licenciar, arrendar, revender, transferir, exhibir públicamente, presentar públicamente, transmitir, retransmitir o explotar de otra forma los Servicios, excepto como se permita expresamente por Hard Production; (iii) descompilar, realizar ingeniería inversa o desmontar los Servicios, excepto como se permita por la ley aplicable; (iv) enlazar, reflejar o enmarcar cualquier parte de los Servicios; (v) causar o lanzar cualquier programa o script con el objeto de extraer, indexar, analizar o de otro modo realizar prospección de datos de cualquier parte de los Servicios o sobrecargar o bloquear indebidamente la operación y/o funcionalidad de cualquier aspecto de los Servicios; o (vi) intentar obtener un acceso no autorizado o dañar cualquier aspecto de los Servicios o sus sistemas o redes relacionados.',

    'provision_services' => 'Prestación de los Servicios.',

    'provision_services_content'=>'Usted reconoce que partes de los Servicios podrán ponerse a disposición bajo varias marcas u opciones de pedidos de Hard Production asociadas con el arte, modelaje, protocolo, stand up comedy, actuación, entretenimiento o los servicios logísticos, incluidas en la marca de Speeho. Así mismo usted reconoce que los Servicios podrán ponerse a disposición bajo dichas marcas u opciones de pedidos por o en relación con: (i) ciertas subsidiarias o afiliados de Hard Production; o (ii) Terceros proveedores independientes, incluidos artistas de empresas con permisos y licencias para prestar servicios.',

    'third_services'=>'Servicios y contenido de Terceros',

    'third_services_content'=>'Los Servicios podrán ponerse a disposición o ser accesible en relación con servicios y contenido de terceros (incluida la publicidad) que Hard Production no controle. Usted reconoce que podrán ser de aplicación diferentes condiciones y políticas de privacidad al uso que haga de dichos servicios y contenido de terceros. Hard Production no respalda dichos servicios y contenido de terceros y en ningún caso Hard Production será responsable de cualquier producto o servicio de dichos terceros proveedores. Adicionalmente, Apple Inc., Google, Inc., Microsoft Corporation o BlackBerry Limited y/o sus correspondientes subsidiarias o afiliados internacionales serán terceros beneficiarios en este contrato si usted accede a los Servicios utilizando Aplicaciones desarrolladas para dispositivos móviles con sistema iOS, Android, Microsoft Windows, respectivamente. Estos terceros beneficiarios no son parte de este contrato y no son responsables de la prestación o apoyo de los Servicios de ninguna manera. Su acceso a los Servicios utilizando estos dispositivos se sujeta a las condiciones establecidas en las condiciones de servicio de terceros beneficiarios aplicables.',

    'ownership'=>'Titularidad',

    'ownership_content'=>'Los Servicios y todos los derechos relativos a estos son y permanecerán de la propiedad de Hard Production o de sus licenciantes. Ninguna de estas condiciones ni su uso de los Servicios le transfiere u otorgan ningún derecho: (i) sobre o en relación con los Servicios, excepto en cuanto a la licencia limitada otorgada anteriormente; o bien (ii) a utilizar o mencionar en cualquier modo a los nombres de empresa, logotipos, nombres de producto y servicio, marcas comerciales o marcas de servicio pertenecientes a Hard Production o de sus licenciantes.',

    'use_services' => '3. Su uso de los Servicios',

    'user_account' => 'Cuentas de usuario.',

    'user_account_content' =>'Con el fin de usar la mayor parte de los aspectos de los Servicios, usted debe registrarse y mantener activa una cuenta personal de usuario de los Servicios (“Cuenta”). Para obtener una Cuenta debe tener como mínimo 18 años, o tener la mayoría de edad legal en su jurisdicción (si es distinta a los 18 años). El registro de la cuenta le requiere que comunique a Hard Production determinada información personal, como su nombre, dirección, número de teléfono móvil, marca (si la tiene) nombre de empresa, corporación o fundación con su número de Nit (si es persona jurídica) Nombre Artístico (Si lo tiene) RUT (si factura a través de este) así como por lo menos un método de pago válido (bien una tarjeta de crédito o bien un socio de pago aceptado). Usted se compromete a mantener la información en su Cuenta de forma exacta, completa y actualizada. Si no mantiene la información de Cuenta de forma exacta, completa y actualizada, incluso el tener un método de pago inválido o que haya vencido, podrá resultar en su imposibilidad para acceder y utilizar los Servicios o en la resolución por parte de Hard Production de este Condiciones celebrado con usted. Usted es responsable de toda la actividad que ocurre en su Cuenta y se compromete a mantener en todo momento de forma segura y secreta el nombre de usuario y la contraseña de su Cuenta. A menos que Hard Production permita otra cosa por escrito, usted solo puede poseer una Cuenta.',

    'user_behavior'=>'Requisitos y conducta del usuario',

    'user_behavior_content'=>'El Servicio no está disponible para el uso de personas menores de 18 años. Usted no podrá autorizar a terceros a utilizar su Cuenta, asimismo no podrá permitir a personas menores de 18 años que reciban servicios artísticos y/o de entretenimiento o logísticos de Terceros proveedores, a menos que aquellos sean acompañados por usted. No podrá ceder o transferir de otro modo su Cuenta a cualquier otra persona o entidad. Usted acuerda cumplir con todas las leyes aplicables al utilizar los Servicios y solo podrá utilizar los Servicios con fines legítimos (p. ej., no para actividades ilegales o peligrosas). En el uso de los Servicios, no causará estorbos, molestias, incomodidades o daños a la propiedad, tanto al Tercero proveedor como a cualquier otra parte. En algunos casos, se le podrá requerir que facilite un documento de identidad u otro elemento de verificación de identidad para el acceso o uso de los Servicios, y usted acepta que se le podrá denegar el acceso o uso de los Servicios si se niega a facilitar el documento de identidad o el elemento de verificación de identidad.',

    'text_messages'=>'Mensajes de texto',

    'text_messages_content'=>'Al crear una Cuenta, usted acepta que los Servicios le puedan enviar mensajes de texto informativos (SMS) como parte de la actividad comercial normal de su uso de los Servicios. Usted podrá solicitar la no recepción de mensajes de texto informativos (SMS) de Speeho – Hard Production en cualquier momento enviando un correo electrónico a soporte@speeho.com indicando que no desea recibir más dichos mensajes, junto con el número de teléfono del dispositivo móvil que recibe los mensajes. Usted reconoce que solicitar la no recepción de mensajes de texto informativos (SMS) podrá afectar al uso que usted haga de los Servicios.',

    'promotional_codes'=>'Códigos promocionales',

    'promotional_codes_content'=>'Hard Production podrá, a su sola discreción, crear códigos promocionales que podrán ser canjeados por crédito de Cuenta u otros elementos o beneficios relacionados con los Servicios y/o los servicios de un Tercero proveedor, con sujeción a cualquier condición adicional que Hard Production establezca sobre la base de cada código promocional (“Códigos promocionales”). Usted acuerda que los Códigos promocionales: (i) deben usarse para la audiencia y el propósito deseado, y de manera lícita; (ii) no podrán duplicarse, venderse o transferirse de ninguna manera, o ponerse a disposición del público general (tanto si se publican en un foro público como de otra forma), a menos que sea con el permiso de Hard Production; (iii) podrán ser invalidados por Hard Production en cualquier momento por cualquier motivo sin responsabilidad para Hard Production; (iv) podrán usarse solo conforme a las condiciones específicas que Hard Production establezca para dicho Código promocional; (v) no son válidos como efectivo; y (vi) podrán caducar antes de que usted los utilice. Hard Production se reserva el derecho de retener o deducir el crédito u otros elementos o beneficios obtenidos a través de la utilización de los Códigos promocionales por usted o cualquier otro usuario en el caso de que Hard Production determine o crea que el uso o el canje de los Códigos promocionales fue de modo erróneo, fraudulento, ilegal o infringiendo las condiciones del Código promocional o las presentes Condiciones.',

    'provided_user'=>'Contenido proporcionado por el Usuario',

    'provided_user_content'=> 'Hard Production podrá, a su sola discreción, permitirle cuando considere oportuno, que envíe, cargue, publique o de otro modo ponga a disposición de Hard Production a través de los Servicios contenido e información de texto, audio y/o visual, incluidos comentarios y opiniones relativos a los Servicios, iniciación de peticiones de apoyo, así como presentación de admisiones para competiciones y promociones (“Contenido de usuario”). Todo Contenido de usuario facilitado por usted seguirá siendo de su propiedad. No obstante, al proporcionar Contenido de usuario a Hard Production, usted otorga una licencia mundial, perpetua, irrevocable, transferible, libre de regalías, con derecho a sublicenciar, usar, copiar, modificar, crear obras derivadas, distribuir, exhibir públicamente, presentar públicamente o de otro modo explotar de cualquier manera dicho Contenido de usuario en todos los formatos y canales de distribución, conocidos ahora o ideados en un futuro (incluidos en relación con los Servicios y el negocio de Hard Production y en sitios y servicios de terceros), sin más aviso o consentimiento de usted y sin requerirse el pago a usted o a cualquier otra persona o entidad.
Usted declara y garantiza que: (i) es el único y exclusivo propietario de todo el Contenido de usuario o que tiene todos los derechos, licencias, consentimientos y permisos necesarios para otorgar a Hard Production la licencia al Contenido de usuario como establecido anteriormente; y (ii) ni el Contenido de usuario ni su presentación, carga, publicación o puesta a disposición de otro modo de dicho Contenido de usuario, ni el uso por parte de Hard Production del Contenido de usuario como está aquí permitido, infringirán, malversarán o violarán la propiedad intelectual o los derechos de propiedad de un tercero o los derechos de publicidad o privacidad o resultarán en la violación de cualquier ley o reglamento aplicable.
Usted acuerda no proporcionar Contenido de usuario que sea difamatorio, calumnioso, odioso, violento, obsceno, pornográfico, ilícito o de otro moMensajes de textodo ofensivo, como determine Hard Production, a su sola discreción, tanto si dicho material pueda estar protegido o no por la ley. Hard Production podrá, a su sola discreción y en cualquier momento y por cualquier motivo, sin avisarle previamente, revisar, controlar o eliminar Contenido de usuario, pero sin estar obligada a ello.',

    'network_devices'=>'Acceso a la red y dispositivos.',

    'network_devices_content'=>'Usted es responsable de obtener el acceso a la red de datos necesario para utilizar los Servicios. Podrán aplicarse las tarifas y tasas de datos y mensajes de su red móvil si usted accede o utiliza los Servicios desde un dispositivo inalámbrico y usted será responsable de dichas tarifas y tasas. Usted es responsable de adquirir y actualizar el hardware compatible o los dispositivos necesarios para acceder y utilizar los Servicios y Aplicaciones y cualquier actualización de estos. Hard Production no garantiza que los Servicios, o cualquier parte de estos, funcionen en cualquier hardware o dispositivo particular. Además, los Servicios podrán ser objeto de disfunciones o retrasos inherentes al uso de Internet y de las comunicaciones electrónicas.',

    'payment' => '4. Pago',

    'payment_content' => 'Usted entiende que el uso de los Servicios puede derivar en cargos por los servicios o bienes que reciba de un Tercer proveedor (“Cargos”). Después de que haya recibido los servicios u obtenido los bienes mediante el uso de los Servicios, Hard Production facilitará su pago de los Cargos aplicables en nombre del Tercero proveedor como agente de cobro limitado del Tercero proveedor. El pago de los Cargos de dicha manera se considerará como el pago efectuado directamente por usted al Tercero proveedor. Los Cargos incluirán los impuestos aplicables cuando se requiera por ley. Los Cargos pagados por usted son definitivos y no reembolsables, a menos que Hard Production determine lo contrario. Usted conserva el derecho de solicitar Cargos más bajos de un Tercero proveedor para los servicios o bienes recibidos por usted de dicho Tercero proveedor en el momento en que reciba dichos servicios o bienes. Hard Production responderá en consecuencia a cualquier solicitud de un Tercero proveedor para modificar los Cargos por un servicio o bien en particular. Los cargos pueden incluir otras cuotas, peajes y/o recargos aplicables, incluyendo cuotas por solicitud, cuotas o cargos municipales, estatales o nacionales/federales, cargos por demoras, recargos aeroportuarios o tarifas de procesamiento por pagos fraccionados, entre otros que sean aplicables. Visite www.speeho.com/cities para obtener más información sobre su ubicación en particular.
Todos los Cargos son pagaderos inmediatamente y el pago se facilitará por Hard Production utilizando al método de pago preferido indicado en su Cuenta, y después de ello Hard Production le enviará un recibo por correo electrónico. Si se determina que el método de pago de su Cuenta principal ha caducado, es inválido o de otro modo no sirve para cobrarle, usted acepta que Hard Production, como agente de cobro limitado del Tercero proveedor, utilice un método de pago secundario en su Cuenta, si estuviera disponible.
Hard Production, en cualquier momento y a su sola discreción, se reserva el derecho de establecer, eliminar y/o revisar los Cargos para alguno o todos los servicios o bienes obtenidos a través del uso de los Servicios. Además, usted reconoce y acepta que los Cargos aplicables en determinadas zonas geográficas podrán incrementar sustancialmente durante los periodos de alta demanda. Hard Production usará los esfuerzos razonables para informarle de los Cargos que podrán aplicarse, siempre y cuando usted sea responsable de los Cargos incurridos en su Cuenta, independientemente de que usted conozca dichos Cargos o los importes de estos. Hard Production podrá, cuando lo considere oportuno, proporcionar a determinados usuarios ofertas promocionales y descuentos que pueden resultar en el cobro de diferentes importes por estos o similares servicios o bienes obtenidos a través del uso de los Servicios, y usted acepta que dichas ofertas promocionales y descuentos, a menos que también se pongan a su disposición, no se tendrán en cuenta en el uso por su parte de los Servicios o los Cargos aplicados a usted. Usted podrá optar por cancelar su solicitud para los servicios o bienes de un Tercero proveedor en cualquier momento antes de la llegada de ese Tercero proveedor, en cuyo caso se le podrá cobrar una tasa de cancelación.
Esta estructura de pago está destinada para compensar plenamente al Tercero proveedor por los servicios o bienes proporcionados. Hard Production no designa ninguna parte de su pago como propina o gratificación al Tercero proveedor. Cualquier manifestación por parte de Hard Production (en la página web de speeho o en los materiales de marketing de speeho – hard production) en el sentido de que dar una propina es “voluntario”, “no requerido”, y/o “incluido” en los pagos que realiza para los servicios o bienes proporcionados no pretende sugerir que Hard Production proporciona importes adicionales, aparte de los descritos anteriormente, al Tercero proveedor. Usted entiende y acepta que, mientras es libre de proporcionar un pago adicional como gratificación a cualquier Tercero proveedor que le proporcione servicios o bienes obtenidos mediante el Servicios, no tiene obligación de ello. Las gratificaciones son voluntarias. Después de que haya recibido los servicios obtenidos a través del Servicio, tendrá la oportunidad de calificar su experiencia y dejar comentarios adicionales sobre el Tercero proveedor.',

    'repair_cleaning_fees'=>'Tarifa de reparación, limpieza o cargos por objetos olvidados.',

    'repair_cleaning_fees_content'=>'Usted será responsable del coste de la reparación por daños o de la limpieza necesaria si llegare a incurrir y ser necesario en establecimientos, teatros, locales de terceros por el uso de los servicios solicitados y las propiedades del Tercero proveedor, que se ocasionen por el uso de los Servicios en su Cuenta que sobrepasen los daños considerados normales por “el desgaste” y la limpieza necesaria (“Reparación o Limpieza”). En el caso de que un Tercero proveedor informe de la necesidad de reparación o limpieza, y dicha reparación o limpieza se verifique por Hard Production a su razonable discreción, Hard Production se reserva el derecho de facilitar el pago por el coste razonable de dicha reparación o limpieza en nombre del Tercero proveedor utilizando su método de pago indicado en su Cuenta. Dichos importes, así como aquellos cargos por la devolución de objetos olvidados, se transferirán por Hard Production al correspondiente Tercero proveedor y no son reembolsables.
Los valores correspondientes a los cargos que se realicen a Usted, por limpieza o devolución de objetos olvidados, los podrá encontrar en https://www.speeho.com/hardproduction-colombia/reparaciones-devoluciones y podrán ser actualizados en todo momento a discreción de Hardproduction.',

    'waivers_indemnity' => '5. Renuncias; Limitación de responsabilidad; Indemnidad.',

    'resignation'=>'RENUNCIA',

    'resignation_content' => 'LOS SERVICIOS SE PROPORCIONAN “TAL CUAL” Y “COMO DISPONIBLES”. HARD PRODUCTION RENUNCIA A TODA DECLARACIÓN Y GARANTÍA, EXPRESA, IMPLÍCITA O ESTATUTARIA, NO EXPRESAMENTE ESTABLECIDA EN ESTAS CONDICIONES, INCLUIDAS LAS GARANTÍAS IMPLÍCITAS DE COMERCIABILIDAD, IDONEIDAD PARA UN FIN PARTICULAR Y NO VIOLACIÓN. ADEMÁS, HARD PRODUCTION NO HACE DECLARACIÓN NI PRESTA GARANTÍA ALGUNA RELATIVA A LA FIABILIDAD, PUNTUALIDAD, CALIDAD, IDONEIDAD O DISPONIBILIDAD DE LOS SERVICIOS O CUALQUIERA DE LOS SERVICIOS SOLICITADOS A TRAVÉS DEL USO DE LOS SERVICIOS, O QUE LOS SERVICIOS NO SERÁN INTERRUMPIDOS O ESTARÁN LIBRES DE ERRORES. HARD PRODUCTION NO GARANTIZA LA CALIDAD, IDONEIDAD, SEGURIDAD O HABILIDAD DE LOS TERCEROS PROVEEDORES. USTED ACUERDA QUE TODO RIESGO DERIVADO DE SU USO DE LOS SERVICIOS Y CUALQUIER SERVICIO O BIEN SOLICITADO EN RELACIÓN CON AQUELLOS SERÁ ÚNICAMENTE SUYO, EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY APLICABLE.',

    'limitation_liability'=>'LIMITACIÓN DE RESPONSABILIDAD',

    'limitation_liability_content'=> 'HARD PRODUCTION NO SERÁ RESPONSABLE DE DAÑOS INDIRECTOS, INCIDENTALES, ESPECIALES, EJEMPLARES, PUNITIVOS O EMERGENTES, INCLUIDOS EL LUCRO CESANTE, LA PÉRDIDA DE DATOS, LA LESIÓN PERSONAL O EL DAÑO A LA PROPIEDAD, NI DE PERJUICIOS RELATIVOS, O EN RELACIÓN CON, O DE OTRO MODO DERIVADOS DE CUALQUIER USO DE LOS SERVICIOS, INCLUSO AUNQUE (SPEEHO) HARD PRODUCTION HAYA SIDO ADVERTIDO DE LA POSIBILIDAD DE DICHOS DAÑOS. HARD PRODUCTION NO SERÁ RESPONSABLE DE CUALQUIER DAÑO, RESPONSABILIDAD O PÉRDIDA QUE DERIVEN DE: (I) SU USO O DEPENDENCIA DE LOS SERVICIOS O SU INCAPACIDAD PARA ACCEDER O UTILIZAR LOS SERVICIOS; O (ii) CUALQUIER TRANSACCIÓN O RELACIÓN ENTRE USTED Y CUALQUIER TERCERO PROVEEDOR, AUNQUE HARD PRODUCTION HUBIERA SIDO ADVERTIDO DE LA POSIBILIDAD DE DICHOS DAÑOS. HARD PRODUCTION NO SERÁ RESPONSABLE DEL RETRASO O DE LA FALTA DE EJECUCIÓN RESULTANTE DE CAUSAS QUE VAYAN MÁS ALLÁ DEL CONTROL RAZONABLE DE HARD PRODUCTION. USTED RECONOCE QUE LOS TERCEROS PROVEEDORES DE SERVICIOS QUE PRESTEN SERVICIOS DE ARTE, PROTOCOLO, PASARELA Y/O ENTRETENIMIENTO SOLICITADOS A TRAVÉS DE ALGUNAS MARCAS DE PEDIDOS PODRÁN OFRECER SERVICIOS COMPARTIDO O/Y PUEDE QUE NO DISPONGAN DE LA LICENCIA O DEL PERMISO PROFESIONAL. EN NINGÚN CASO LA RESPONSABILIDAD TOTAL DE HARD PRODUCTION HACIA USTED EN RELACIÓN CON LOS SERVICIOS POR TODOS LOS DAÑOS, LAS PÉRDIDAS Y LOS JUICIOS PODRÁ EXCEDER DE QUINIENTOS EUROS (€500).
USTED PODRÁ UTILIZAR LOS SERVICIOS DE HARD PRODUCTION PARA SOLICITAR Y PLANIFICAR SERVICIOS DE ARTE, PROTOCOLO, PASARELA Y/O ENTRETENIMIENTO O LOGÍSTICOS CON TERCEROS PROVEEDORES, PERO ACEPTA QUE HARD PRODUCTION NO TIENE RESPONSABILIDAD ALGUNA HACIA USTED EN RELACIÓN CON CUALQUIER SERVICIO DE, ARTE, PROTOCOLO, PASARELA Y/O ENTRETENIMIENTO O LOGÍSTICOS PRESTADO A USTED POR TERCEROS PROVEEDORES QUE NO SEA COMO SE HA ESTABLECIDO EXPRESAMENTE EN ESTAS CONDICIONES.
LAS LIMITACIONES Y LA RENUNCIA EN ESTE APARTADO 5 NO PRETENDEN LIMITAR LA RESPONSABILIDAD O ALTERAR SUS DERECHOS COMO CONSUMIDOR QUE NO PUEDAN EXCLUIRSE SEGÚN LA LEY APLICABLE.',

    'indemnity'=>'Indemnidad',

    'indemnity_content'=>'Usted acuerda mantener indemnes y responder frente a Hard Production y sus consejeros, directores, empleados y agentes por cualquier reclamación, demanda, pérdida, responsabilidad y gasto (incluidos los honorarios de abogados) que deriven de: (i) su uso de los Servicios o servicios o bienes obtenidos a través de su uso de los Servicios; (ii) su incumplimiento o violación de cualquiera de estas Condiciones; (iii) el uso por parte de Hard Production de su Contenido de usuario; o (iv) su infracción de los derechos de cualquier tercero, incluidos Terceros proveedores.',

    'applicable_legislation' => '6. Legislación aplicable; Arbitraje.',

    'applicable_legislation_content'=>'Salvo que aquí se especifique lo contrario, las presentes Condiciones se regirán e interpretarán exclusivamente en virtud de la legislación Colombiana, con exclusión de sus normas sobre conflicto de leyes. La Convención de Viena sobre los Contratos de Compraventa Internacional de Mercaderías de 1980 (CISG) no se aplicará. Cualquier disputa, conflicto, reclamación o controversia, del tipo que sea, que resulte de las presentes Condiciones o que se relacione en gran parte con ellas, incluyendo las relativas a su validez, interpretación y exigibilidad (cualquier “Disputa”), deberán someterse forzosamente a procedimientos de conciliación extrajudicial y/o mediación en virtud del Reglamento de Mediación de la Cámara de Comercio de Bogotá (“Reglamento de Mediación de la CCB”). Si dicha disputa no fuese solucionada en un plazo de sesenta (60) días desde la fecha en la que se formalice la solicitud de mediación en virtud del Reglamento de Mediación de la CCB, se hará referencia a dicha disputa y se solucionará exclusiva y definitivamente mediante arbitraje en virtud del Reglamento de Arbitraje de la Cámara de Comercio de Bogotá (“Reglamento de Arbitraje de la CCB). Las disposiciones sobre Proceso Expedito y del Árbitro de Emergencia del Reglamento de la CCB no se aplicarán. La disputa será resuelta por un (1) árbitro nombrado a tal fin en virtud del Reglamento de la CCB. El lugar tanto para la mediación como para el arbitraje será Bogotá D.C., Colombia, sin perjuicio de cualquier derecho que usted pudiera tener según la normatividad Colombiana. El idioma de mediación y/o arbitraje será el español, a no ser que usted no hable español, en cuyo caso la mediación y/o el arbitraje se llevarán a cabo en español y en su idioma materno. La existencia y el contenido de los procedimientos de mediación y arbitraje, incluidos los documentos e informes presentados por las partes, la correspondencia de la CCB, la correspondencia del mediador y la correspondencia, los pedidos y los laudos emitidos por el único árbitro deberán permanecer en estricta confidencialidad y no deberán ser revelados a ningún tercero sin el consentimiento expreso por escrito de la otra parte, a menos que: (i) la revelación al tercero sea razonablemente necesaria para llevar a cabo el procedimiento de mediación o arbitraje; y (ii) el tercero acepte incondicionalmente por escrito estar sujeto a la obligación de confidencialidad estipulada en el presente documento.',

    'other_provisions' => '7. Otras disposiciones',

    'copyright_claims' =>'Reclamaciones por infracción de derechos de autor',

    'copyright_claims_content' =>'Las reclamaciones por infracción de derechos de autor deberán enviarse al agente designado de Hard Production. Visite la página web de speeho en https://www.speeho.com/legal para obtener las direcciones designadas e información adicional.',

    'notifications'=>'Notificaciones',

    'notifications_content'=>'Hard Production podrá notificar por medio de una notificación general en los Servicios, mediante un correo electrónico enviado a su dirección electrónica en su Cuenta o por comunicación escrita enviada a su dirección, según lo dispuesto en su Cuenta. Usted podrá notificar a Hard Production por comunicación escrita a la dirección de Hard Production Calle 7b # 69d - 26 Barrio Marcella, Bogotá D.C., Colombia.',

    'general_disposition' => 'Disposiciones generales',

    'general_disposition_content' => 'No podrá ceder ni transferir estas Condiciones, en todo o en parte, sin el consentimiento previo por escrito de Hard Production. Usted da su aprobación a Hard Production para ceder o transferir estas Condiciones, en todo o en parte, incluido a: (i) una subsidiaria o un afiliado; (ii) un adquirente del capital, del negocio o de los activos de Hard Production; o (iii) un sucesor por fusión. No existe entre usted, Hard Production o cualquier Tercer proveedor una empresa conjunta o relación de socios, empleo o agencia como resultado del contrato entre usted y Hard Production o del uso de los Servicios.
Si cualquier disposición de estas Condiciones se considerara ilegal, nula o inexigible, ya sea en su totalidad o en parte, de conformidad con cualquier legislación, dicha disposición o parte de esta se considerará que no forma parte de estas Condiciones, aunque la legalidad, validez y exigibilidad del resto de las disposiciones de estas Condiciones no se verá afectada. En ese caso, las partes deberán reemplazar dicha disposición ilegal, nula o inexigible, en todo o en parte por una disposición legal, válida y exigible que tenga, en la medida de lo posible, un efecto similar al que tenía la disposición ilegal, nula o inexigible, dados los contenidos y el propósito de estas Condiciones. Estas Condiciones constituyen el contrato íntegro y el entendimiento entre las partes en relación con el objeto y sustituye y reemplaza a todos los contratos o acuerdos anteriores o contemporáneos en relación con dicho objeto. En estas Condiciones, las palabras “incluido/a/os/as” e “incluye/n” significan “incluido, de forma meramente enunciativa”.'

];